// about.c
#define IDD_ABOUT_VERSION       50
#define IDD_ABOUT_ICON          51
#define IDD_ABOUT_STRING1       52
#define IDD_ABOUT_STRING2       53
#define IDD_CREDITS				54
#define IDD_THANKS				55
#define IDD_CHANGES				56
#define IDD_LGPL				57


// assist.c
#define IDD_ASSIST_TYPE         60
#define IDD_ASSIST_1            61
#define IDD_ASSIST_2            62
#define IDD_ASSIST_3            63
#define IDD_ASSIST_4            64
#define IDD_ASSIST_DEFAULT      65

// boardcfg.c
#define IDD_BOARD_LIST          100
#define IDD_BOARD_CONFIGURE     101
#define IDD_BOARD_DEFAULT       102
#define IDD_BOARD_DEFAULT_OLD   103
#define IDD_BOARD_SQUARE        104
#define IDD_BOARD_PIECE         105

// butcfg.c
#define IDD_BUTTON_EXTENDED     200
#define IDD_BUTTON              201
#define IDD_BUTTON_LABEL        202
#define IDD_BUTTON_FUNCTION     203
#define IDD_BUTTON_COMMAND      204
#define IDD_BUTTON_FONT         205
#define IDD_BUTTON_DEFAULT      206
#define IDD_BUTTON_CHESS        207
#define IDD_BUTTON_OLDFICS      208
#define IDD_BUTTON_NEWFICS      209

// censor.c
#define IDD_CENSOR_APPLY        220
#define IDD_CENSOR_LIST         221
#define IDD_CENSOR_HANDLE       222
#define IDD_CENSOR_BIT1         223
#define IDD_CENSOR_BIT2         224
#define IDD_CENSOR_BIT3         225
#define IDD_CENSOR_BIT4         226
#define IDD_CENSOR_BIT5         227
#define IDD_CENSOR_BIT6         228
#define IDD_CENSOR_BIT7         229
#define IDD_CENSOR_BIT8         230
#define IDD_CENSOR_BIT9         231
#define IDD_CENSOR_BIT10        232
#define IDD_CENSOR_BIT11        233
#define IDD_CENSOR_TELL         234
#define IDD_CENSOR_PTELL        235
#define IDD_CENSOR_SAY          236
#define IDD_CENSOR_PARTNER      237
#define IDD_CENSOR_NEW          238
#define IDD_CENSOR_DELETE       239
#define IDD_CENSOR_EDIT         240
#define IDD_CENSOR_MESSAGE      241

// ctrlkey.c
#define IDD_CONTROL_LIST        250
#define IDD_CONTROL_FUNCTION    251
#define IDD_CONTROL_COMMAND     252
#define IDD_CONTROL_DEFAULT     253
#define IDD_CONTROL_DEFAULT1    254

// earcfg.c / gamecfg.c / sndcfg.c
#define IDD_SOUND_APPLY         300
#define IDD_SOUND               301
#define IDD_MATCH               302
#define IDD_BEEP                303
#define IDD_WAVE                304
#define IDD_BROWSE              305
#define IDD_PLAY                306
#define IDD_SND_DEFAULT         307
#define IDD_EAR_OLDFICS         308
#define IDD_EAR_NEWFICS         309

// fkey.c
#define IDD_FUNCTION_LIST       400
#define IDD_FUNCTION_FUNCTION   401
#define IDD_FUNCTION_COMMAND    402
#define IDD_FUNCTION_DEFAULT    403

// gameevnt.c
#define IDD_GAME_EVENT          500
#define IDD_GAME_EVENT1         501
#define IDD_GAME_EVENT2         502
#define IDD_GAME_EVENT_DEFAULT  503

// gdisplay.c
#define IDD_GDISPLAY_1          520
#define IDD_GDISPLAY_2          521
#define IDD_GDISPLAY_3          522
#define IDD_GDISPLAY_4          523
#define IDD_GDISPLAY_5          524
#define IDD_GDISPLAY_6          525
#define IDD_GDISPLAY_7          526
#define IDD_GDISPLAY_8          527
#define IDD_GDISPLAY_9          528
#define IDD_GDISPLAY_10         529
#define IDD_GDISPLAY_11         530
#define IDD_GDISPLAY_12         531
#define IDD_GDISPLAY_13         532
#define IDD_GDISPLAY_14         533
#define IDD_GDISPLAY_15         534
#define IDD_GDISPLAY_16         535
#define IDD_GDISPLAY_17         536
#define IDD_GDISPLAY_18         537
#define IDD_GDISPLAY_19         538
#define IDD_GDISPLAY_20         539

// goption.c
#define IDD_GOPTION_1           550
#define IDD_GOPTION_2           551
#define IDD_GOPTION_3           552
#define IDD_GOPTION_4           553
#define IDD_GOPTION_5           554
#define IDD_GOPTION_6           555
#define IDD_GOPTION_7           556
#define IDD_GOPTION_8           557
#define IDD_GOPTION_9           558
#define IDD_GOPTION_10          559
#define IDD_GOPTION_11          560
#define IDD_GOPTION_12          561
#define IDD_GOPTION_13          562
#define IDD_GOPTION_14			564
#define IDD_GOPTION_15			565

// lagcmd.c
#define IDD_LAG_COMMAND_APPLY   600
#define IDD_LAG_TOLERANCE       601
#define IDD_LAG_THRESHOLD       602
#define IDD_LAG_FUNCTION        603
#define IDD_LAG_COMMAND         604
#define IDD_LAG_DISPLAY         605
#define IDD_LAG_DEFAULT         606

// logevent.c
#define IDD_LOGIN_EVENT         650
#define IDD_LOGIN_EVENT1        651
#define IDD_LOGIN_EVENT2        652
#define IDD_LOGIN_EVENT_DEFAULT 653

// match.c / seek.c
#define IDD_OPPONENT            700
#define IDD_INITIAL             701
#define IDD_INCREMENT           702
#define IDD_RATED               703
#define IDD_TYPE                704
#define IDD_COLOR               705
#define IDD_RATING1             706
#define IDD_RATING2             707
#define IDD_MANUAL              708
#define IDD_FORMULA             709

// message.c
#define IDD_RECIPIENT           710
#define IDD_MESSAGE             711

// minput.c
#define IDD_MOVEINPUT_1         730
#define IDD_MOVEINPUT_2         731
#define IDD_MOVEINPUT_3         732
#define IDD_MOVEINPUT_4         733
#define IDD_MOVEINPUT_5         734
#define IDD_MOVEINPUT_6         735
#define IDD_MOVEINPUT_7         736
#define IDD_MOVEINPUT_8         737
#define IDD_MOVEINPUT_9         738
#define IDD_MOVEINPUT_10        739
#define IDD_MOVEINPUT_11        740
#define IDD_MOVEINPUT_12        741
#define IDD_MOVEINPUT_13        742
#define IDD_MOVEINPUT_14        743
#define IDD_MOVEINPUT_15        744

// movebut.c
#define IDD_MOVEBUTTON_1        770
#define IDD_MOVEBUTTON_2        771
#define IDD_MOVEBUTTON_3        772

// newlogin.c / oldlogin.c
#define IDD_NAME                800
#define IDD_SERVER              801
#define IDD_SERVER_CONFIGURE    802
#define IDD_HELPER              803
#define IDD_HELPER_BROWSE       804
#define IDD_HANDLE              805
#define IDD_PASSWORD            806
#define IDD_SCRIPT              807
#define IDD_SCRIPT_BROWSE       808

// password

#define IDD_PWD_DIALOG_TEXT     1600
#define IDD_PWD_TEXT            1601

// promote.c
#define IDD_QUEEN               900
#define IDD_ROOK                901
#define IDD_BISHOP              902
#define IDD_KNIGHT              903
#define IDD_KING                904

// question.c
#define IDD_QUESTION            950

// redclock.c
#define IDD_REDCLOCK_1          1000
#define IDD_REDCLOCK_2          1001
#define IDD_REDCLOCK_3          1002
#define IDD_REDCLOCK_4          1003
#define IDD_REDCLOCK_5          1004

// rightm.c
#define IDD_RM_LIST             1020
#define IDD_RM_MENU             1021
#define IDD_RM_FUNCTION         1022
#define IDD_RM_COMMAND          1023
#define IDD_RM_NEW              1024
#define IDD_RM_EDIT             1025
#define IDD_RM_DELETE           1026
#define IDD_RM_DEFAULT          1027
#define IDD_RM_UP               1028
#define IDD_RM_DOWN             1029

// savegame.c
#define IDD_SAVEGAME_1          1030
#define IDD_SAVEGAME_2          1031
#define IDD_SAVEGAME_3          1032
#define IDD_SAVEGAME_4          1033
#define IDD_SAVEGAME_5          1034
#define IDD_SAVEGAME_6          1035
#define IDD_SAVEGAME_7          1036
#define IDD_SAVEGAME_8          1037
#define IDD_SAVEGAME_9          1038
#define IDD_SAVEGAME_10         1039
#define IDD_SAVEGAME_11         1040

// server.c
#define IDD_SERVER_DEFINE       1050
#define IDD_SERVER_ADDRESS      1051
#define IDD_SERVER_PORT         1052
#define IDD_SERVER_PROMPT       1053
#define IDD_SERVER_TYPE         1054
#define IDD_SERVER_NEW          1055
#define IDD_SERVER_EDIT         1056
#define IDD_SERVER_DELETE       1057
#define IDD_SERVER_DEFAULT      1058
#define IDD_SERVER_UP           1059
#define IDD_SERVER_DOWN         1060

// silence.c
#define IDD_SILENCE_APPLY		1500
#define IDD_SILENCE_SHOUT       1501
#define IDD_SILENCE_CSHOUT		1502
#define IDD_SILENCE_ANNOUNCE	1503
#define IDD_SILENCE_CHTELL		1504
#define IDD_SILENCE_PETELL		1505
#define IDD_SILENCE_SAY			1506
#define IDD_SILENCE_KIBITZ		1507
#define IDD_SILENCE_WHISPER		1508
#define IDD_SILENCE_PLSHOUT     1511
#define IDD_SILENCE_PLCSHOUT	1512
#define IDD_SILENCE_PLANNOUNCE	1513
#define IDD_SILENCE_PLCHTELL	1514
#define IDD_SILENCE_PLPETELL	1515
#define IDD_SILENCE_PLSAY		1516
#define IDD_SILENCE_PLKIBITZ	1517
#define IDD_SILENCE_PLWHISPER	1518
#define IDD_SILENCE_TELL		1520
#define IDD_SILENCE_DEFAULT     1521

// sitpiece.c
#define IDD_SITPIECE_DROP_MOVE  1080
#define IDD_SITPIECE_FUNCTION   1090

// telcfg.c
#define IDD_TELNET_LIST         1100
#define IDD_TELNET_TEXT         1101
#define IDD_TELNET_CONFIGURE    1102
#define IDD_TELNET_DEFAULT      1103
#define IDD_TELNET_MUSOT        1104
#define IDD_TELNET_ALTHEAS      1105
#define IDD_TELNET_SLICS        1106
#define IDD_TELNET_CHANNEL      1107
#define IDD_TELNET_ADD          1108
#define IDD_TELNET_DELETE       1109

// tell.c
#define IDD_TELL_RECIPIENT      1150
#define IDD_TELL                1151

// timercfg.c
#define IDD_TIMER_MINUTE        1200
#define IDD_TIMER_FUNCTION      1201
#define IDD_TIMER_COMMAND       1202
#define IDD_TIMER_ICC_COMMAND   1203
#define IDD_TIMER_DEFAULT       1204

// timesnd.c
#define IDD_FINAL_APPLY         1300
#define IDD_FINAL_SOUND         1301
#define IDD_FINAL_EDIT          1302
#define IDD_FINAL_BROWSE        1303
#define IDD_FINAL_PLAY          1304
#define IDD_FINAL_DEFAULT1      1305
#define IDD_FINAL_DEFAULT2      1306

// toption.c
#define IDD_TOPTION_1           1350
#define IDD_TOPTION_2           1351
#define IDD_TOPTION_3           1352
#define IDD_TOPTION_4           1353
#define IDD_TOPTION_5           1354
#define IDD_TOPTION_6           1355
#define IDD_TOPTION_7           1356
#define IDD_TOPTION_8           1357
#define IDD_TOPTION_9           1358
#define IDD_TOPTION_10          1359
#define IDD_TOPTION_11          1360
#define IDD_TOPTION_12          1361
#define IDD_TOPTION_13          1362
#define IDD_TOPTION_14          1363
#define IDD_TOPTION_15          1364

// try.c
#define IDD_TRY_LIST            1370
#define IDD_TRY_SCREEN          1371
#define IDD_TRY_TASKBAR         1372
#define IDD_TRY_PLAY            1373

// vars.c
#define IDD_VAR_TEXT            1400
#define IDD_VAR1                1401
