#include "global.h"
#include "fics.h"
#include "icc.h"
#include "nonfics.h"
#include "function.h"
#include "dialog.h"

#pragma warning(disable: 4996)	// Unsafe use of strcpy, sprintf, etc.
#pragma warning(disable: 6031)	// Return value ignored: 'sscanf'
#pragma warning(disable: 6054)	// String 'xyz' might not be zero-terminated
#pragma warning(disable: 6269)	// Possibly incorrect order of operations: dereference ignored